from pydantic import BaseModel, Field, ConfigDict, EmailStr, field_validator
from typing import List, Optional, Dict, Any, Literal
from datetime import datetime, timezone
import uuid


# ─── Public / Seed Models ─────────────────────────────────

class Clinic(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    city_slug: str
    city_name: str
    treatments_supported: List[str] = []
    is_active: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class LeadCreate(BaseModel):
    """Lead create payload. Accepts but does not require the full attribution
    payload generated by `frontend/lib/attribution.ts`. Attribution fields are
    optional — old/legacy submissions still work."""
    model_config = ConfigDict(extra="ignore")
    city_slug: str = Field(min_length=1, max_length=50)
    treatment_type: str = Field(min_length=1, max_length=50)
    answers: Dict[str, Any] = {}
    can_travel: bool = True
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    consent: bool = False
    source: Optional[str] = Field(default=None, max_length=100)
    utm_source: Optional[str] = Field(default=None, max_length=200)
    utm_campaign: Optional[str] = Field(default=None, max_length=200)
    utm_adset: Optional[str] = Field(default=None, max_length=200)
    utm_ad: Optional[str] = Field(default=None, max_length=200)
    page_path: Optional[str] = Field(default=None, max_length=500)

    # Coerce empty / whitespace-only strings to None BEFORE Pydantic
    # tries to validate them as `EmailStr`. Frontend lead-capture forms
    # (MasterQuiz, TreatmentQuiz, AlignersVsBracesQuiz, the per-city /
    # treatment quiz, LeadCaptureForm) all default the email input to
    # `""` and currently submit that empty string when the patient
    # leaves the field blank — `EmailStr` would otherwise reject it
    # with HTTP 422 and break the entire onboarding.
    @field_validator("email", "name", "phone", mode="before")
    @classmethod
    def _coerce_blank_string_to_none(cls, v):
        if isinstance(v, str) and not v.strip():
            return None
        return v

    # ─── First-touch attribution (immutable) ────────────────────────
    first_utm_source: Optional[str] = Field(default=None, max_length=300)
    first_utm_medium: Optional[str] = Field(default=None, max_length=200)
    first_utm_campaign: Optional[str] = Field(default=None, max_length=300)
    first_utm_adset: Optional[str] = Field(default=None, max_length=300)
    first_utm_ad: Optional[str] = Field(default=None, max_length=300)
    first_utm_campaign_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_adset_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_ad_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_content: Optional[str] = Field(default=None, max_length=300)
    first_utm_term: Optional[str] = Field(default=None, max_length=300)
    first_fbclid: Optional[str] = Field(default=None, max_length=300)
    first_gclid: Optional[str] = Field(default=None, max_length=300)
    first_msclkid: Optional[str] = Field(default=None, max_length=300)
    first_ttclid: Optional[str] = Field(default=None, max_length=300)
    first_landing_page: Optional[str] = Field(default=None, max_length=1000)
    first_landing_page_type: Optional[str] = Field(default=None, max_length=50)
    first_referrer: Optional[str] = Field(default=None, max_length=1000)
    first_lead_source_type: Optional[str] = Field(default=None, max_length=50)
    first_article_slug: Optional[str] = Field(default=None, max_length=300)
    first_article_title: Optional[str] = Field(default=None, max_length=500)
    first_seen_at: Optional[str] = Field(default=None, max_length=50)
    original_lead_source_type: Optional[str] = Field(default=None, max_length=50)

    # ─── Latest-touch attribution ────────────────────────
    latest_utm_source: Optional[str] = Field(default=None, max_length=300)
    latest_utm_medium: Optional[str] = Field(default=None, max_length=200)
    latest_utm_campaign: Optional[str] = Field(default=None, max_length=300)
    latest_utm_adset: Optional[str] = Field(default=None, max_length=300)
    latest_utm_ad: Optional[str] = Field(default=None, max_length=300)
    latest_utm_campaign_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_adset_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_ad_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_content: Optional[str] = Field(default=None, max_length=300)
    latest_utm_term: Optional[str] = Field(default=None, max_length=300)
    latest_fbclid: Optional[str] = Field(default=None, max_length=300)
    latest_gclid: Optional[str] = Field(default=None, max_length=300)
    latest_msclkid: Optional[str] = Field(default=None, max_length=300)
    latest_ttclid: Optional[str] = Field(default=None, max_length=300)
    latest_landing_page: Optional[str] = Field(default=None, max_length=1000)
    latest_landing_page_type: Optional[str] = Field(default=None, max_length=50)
    latest_referrer: Optional[str] = Field(default=None, max_length=1000)
    latest_lead_source_type: Optional[str] = Field(default=None, max_length=50)
    latest_article_slug: Optional[str] = Field(default=None, max_length=300)
    latest_article_title: Optional[str] = Field(default=None, max_length=500)
    last_seen_at: Optional[str] = Field(default=None, max_length=50)

    # ─── Conversion data ────────────────────────
    content_path_before_conversion: Optional[List[Dict[str, Any]]] = None
    pages_viewed_before_conversion: Optional[int] = None
    blog_assisted_conversion: Optional[bool] = None
    internal_content_assisted_conversion: Optional[bool] = None
    conversion_page: Optional[str] = Field(default=None, max_length=1000)
    submitted_at: Optional[str] = Field(default=None, max_length=50)
    time_to_submit_seconds: Optional[int] = None


class LeadContactUpdate(BaseModel):
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    consent: bool = False


# ─── Patient layer P4: request-call ───────────────────────────────
# Body for POST /api/leads/{lead_id}/request-call. The endpoint enforces
# `consent_to_share=True` and that `clinic_id` belongs to the lead's
# recommended set. Phone validation is intentionally permissive (digit
# count check + optional `+` prefix) — matches existing platform rules
# for `LeadContactUpdate` while preventing empty / placeholder input.
RequestCallSource = Literal["matching_card", "clinic_profile"]


class RequestCallBody(BaseModel):
    model_config = ConfigDict(extra="ignore")
    clinic_id: str = Field(min_length=1, max_length=200)
    phone: str = Field(min_length=4, max_length=50)
    consent_to_share: bool
    source: RequestCallSource = "matching_card"


# ─── Patient layer P5: assisted choice ────────────────────────────
AssistedChoiceSource = Literal["matching_page", "clinic_profile"]


class RequestZubiteHelpBody(BaseModel):
    """`POST /api/leads/{lead_id}/request-zubite-help` payload.
    Mutual exclusion with `RequestCallBody` is enforced server-side."""
    model_config = ConfigDict(extra="ignore")
    phone: str = Field(min_length=4, max_length=50)
    consent_to_share: bool
    # Optional free-text note. Bounded length to keep DB rows compact
    # and prevent abuse; PII redaction is admin's responsibility.
    message: Optional[str] = Field(default=None, max_length=1000)
    source: AssistedChoiceSource = "matching_page"


class Lead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    city_slug: str
    treatment_type: str
    score_total: int = 0
    band: str = "RED"
    status: str = "NEW"
    assigned_clinic_id: Optional[str] = None
    name: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    consent: bool = False
    answers: Dict[str, Any] = {}
    score_breakdown: Dict[str, int] = {}
    can_travel: bool = True
    utm_source: Optional[str] = None
    utm_campaign: Optional[str] = None
    utm_adset: Optional[str] = None
    utm_ad: Optional[str] = None
    page_path: Optional[str] = None
    notes: Optional[str] = None
    # ─── Attribution (Feb 2026) — see /app/frontend/lib/attribution.ts ───
    # First-touch
    first_utm_source: Optional[str] = None
    first_utm_medium: Optional[str] = None
    first_utm_campaign: Optional[str] = None
    first_utm_adset: Optional[str] = None
    first_utm_ad: Optional[str] = None
    first_utm_campaign_id: Optional[str] = None
    first_utm_adset_id: Optional[str] = None
    first_utm_ad_id: Optional[str] = None
    first_utm_content: Optional[str] = None
    first_utm_term: Optional[str] = None
    first_fbclid: Optional[str] = None
    first_gclid: Optional[str] = None
    first_msclkid: Optional[str] = None
    first_ttclid: Optional[str] = None
    first_landing_page: Optional[str] = None
    first_landing_page_type: Optional[str] = None
    first_referrer: Optional[str] = None
    first_lead_source_type: Optional[str] = None
    first_article_slug: Optional[str] = None
    first_article_title: Optional[str] = None
    first_seen_at: Optional[str] = None
    original_lead_source_type: Optional[str] = None
    # Latest-touch
    latest_utm_source: Optional[str] = None
    latest_utm_medium: Optional[str] = None
    latest_utm_campaign: Optional[str] = None
    latest_utm_adset: Optional[str] = None
    latest_utm_ad: Optional[str] = None
    latest_utm_campaign_id: Optional[str] = None
    latest_utm_adset_id: Optional[str] = None
    latest_utm_ad_id: Optional[str] = None
    latest_utm_content: Optional[str] = None
    latest_utm_term: Optional[str] = None
    latest_fbclid: Optional[str] = None
    latest_gclid: Optional[str] = None
    latest_msclkid: Optional[str] = None
    latest_ttclid: Optional[str] = None
    latest_landing_page: Optional[str] = None
    latest_landing_page_type: Optional[str] = None
    latest_referrer: Optional[str] = None
    latest_lead_source_type: Optional[str] = None
    latest_article_slug: Optional[str] = None
    latest_article_title: Optional[str] = None
    last_seen_at: Optional[str] = None
    # Conversion data
    content_path_before_conversion: Optional[List[Dict[str, Any]]] = None
    pages_viewed_before_conversion: Optional[int] = None
    blog_assisted_conversion: Optional[bool] = None
    internal_content_assisted_conversion: Optional[bool] = None
    conversion_page: Optional[str] = None
    submitted_at: Optional[str] = None
    time_to_submit_seconds: Optional[int] = None
    # ─── Soft duplicate detection (Phase 2C) ────────────────────
    # Non-blocking flag: a new lead is always created; admins use these
    # fields to triage. Never exposed in public or clinic endpoints.
    is_potential_duplicate: bool = False
    duplicate_reason: Optional[str] = None
    possible_duplicate_lead_id: Optional[str] = None


# ─── Admin Models ──────────────────────────────────────────

class LeadStatusUpdate(BaseModel):
    status: Optional[str] = None
    assigned_clinic_id: Optional[str] = None
    notes: Optional[str] = None

    @field_validator("status")
    @classmethod
    def _validate_status(cls, v: Optional[str]) -> Optional[str]:
        return _validate_lead_status(v)


class LeadUpdate(BaseModel):
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    city_slug: Optional[str] = Field(default=None, max_length=50)
    status: Optional[str] = Field(default=None, max_length=50)
    notes: Optional[str] = Field(default=None, max_length=5000)

    @field_validator("status")
    @classmethod
    def _validate_status(cls, v: Optional[str]) -> Optional[str]:
        return _validate_lead_status(v)


# ─── Lead status allow-list (Phase 2A) ────────────────────────────
# Backward-compatible: existing DB only contains NEW and CONTACTED.
# Reject anything outside this set with a 422 from Pydantic.
LEAD_STATUS_ALLOWED = frozenset({"NEW", "CONTACTED", "SCHEDULED", "COMPLETED", "CANCELLED"})


def _validate_lead_status(v: Optional[str]) -> Optional[str]:
    if v is None:
        return v
    if not isinstance(v, str):
        raise ValueError("status must be a string")
    if v not in LEAD_STATUS_ALLOWED:
        raise ValueError(
            f"status must be one of {sorted(LEAD_STATUS_ALLOWED)}; got '{v}'"
        )
    return v


class AdminLogin(BaseModel):
    username: str = Field(min_length=1, max_length=200)
    password: str = Field(min_length=1, max_length=200)


class AdminUser(BaseModel):
    id: str
    username: str
    role: str = "admin"


class TokenResponse(BaseModel):
    # access_token + token_type are only populated when AUTH_REQUIRE_COOKIE=0
    # (Bearer/cookie compatibility mode). In cookie-only mode they are omitted
    # entirely from the response body — the JWT lives in the httpOnly cookie.
    access_token: Optional[str] = None
    token_type: Optional[str] = None
    user: AdminUser


# ─── Clinic Models ─────────────────────────────────────────

class ClinicLogin(BaseModel):
    email: EmailStr
    password: str = Field(min_length=1, max_length=200)


class ClinicUserOut(BaseModel):
    id: str
    clinic_name: str
    city: str
    email: str
    phone: str
    status: str
    address: Optional[str] = None
    website: Optional[str] = None
    company_name: Optional[str] = None
    eik: Optional[str] = None
    mol: Optional[str] = None
    description: Optional[str] = None


class ClinicTokenResponse(BaseModel):
    # Same semantics as `TokenResponse` — populated only when
    # AUTH_REQUIRE_COOKIE=0.
    access_token: Optional[str] = None
    token_type: Optional[str] = None
    user: ClinicUserOut


class ClinicProfileUpdate(BaseModel):
    clinic_name: Optional[str] = None
    phone: Optional[str] = None
    city: Optional[str] = None
    address: Optional[str] = None
    website: Optional[str] = None
    company_name: Optional[str] = None
    eik: Optional[str] = None
    mol: Optional[str] = None
    description: Optional[str] = None


class ClinicPasswordChange(BaseModel):
    current_password: str = Field(min_length=1, max_length=200)
    new_password: str = Field(min_length=8, max_length=200)


class ClinicLeadStatusUpdate(BaseModel):
    status: str


# ─── Phase 2B — Destructive endpoint confirmation bodies ─────────
# Each destructive admin endpoint requires a fixed confirmation phrase to
# guard against accidental fat-finger curl/UI calls.
RESET_ANALYTICS_TOKEN = "CONFIRM_RESET_ANALYTICS"
RESET_BLOG_VIEWS_TOKEN = "CONFIRM_RESET_BLOG_VIEWS"
CLEANUP_LEADS_TOKEN = "CONFIRM_DELETE_NON_MATCHING_LEADS"


class ConfirmationBody(BaseModel):
    """Body shared by reset-analytics / reset-blog-views."""
    confirmation_token: str = Field(min_length=1, max_length=200)


class CleanupLeadsBody(BaseModel):
    """Body for the cleanup-leads endpoint. Requires:
      - explicit non-empty keep_ids
      - explicit confirmation phrase
      - force=True if the operation would delete >50% of the leads
    """
    confirmation_token: str = Field(min_length=1, max_length=200)
    keep_ids: List[str] = Field(min_length=1)
    force: bool = False

    @field_validator("keep_ids")
    @classmethod
    def _no_empty_ids(cls, v: List[str]) -> List[str]:
        cleaned = [s for s in v if isinstance(s, str) and s.strip()]
        if not cleaned:
            raise ValueError("keep_ids must be a non-empty list of strings")
        return cleaned


class ClinicApplicationCreate(BaseModel):
    clinic_name: str = Field(min_length=2, max_length=200)
    city: str = Field(min_length=2, max_length=100)
    address: str = Field(min_length=2, max_length=500)
    website: Optional[str] = Field(default=None, max_length=500)
    contact_name: str = Field(min_length=2, max_length=200)
    phone: str = Field(min_length=5, max_length=50)
    email: EmailStr
    offers_aligners: bool = False
    offers_braces: bool = False
    offers_implants: bool = False
    treats_adults: bool = False
    treats_children: bool = False
    years_experience: Optional[int] = Field(default=None, ge=0, le=100)
    number_of_cases_per_month: Optional[str] = Field(default=None, max_length=100)
    do_you_use_digital_scans: Optional[bool] = None
    what_types_of_patients_are_best_for_you: Optional[str] = Field(default=None, max_length=2000)
    average_response_time: Optional[str] = Field(default=None, max_length=100)


# ─── Blog Models ───────────────────────────────────────────

class FaqItem(BaseModel):
    q: str = Field(min_length=1, max_length=500)
    a: str = Field(min_length=1, max_length=5000)


class LinkItem(BaseModel):
    label: str = Field(min_length=1, max_length=200)
    url: str = Field(min_length=1, max_length=1000)


class SourceItem(BaseModel):
    title: str = Field(min_length=1, max_length=300)
    url: str = Field(min_length=1, max_length=1000)


class CtaBlock(BaseModel):
    title: Optional[str] = Field(default=None, max_length=300)
    text: Optional[str] = Field(default=None, max_length=2000)
    button: Optional[str] = Field(default=None, max_length=200)
    url: Optional[str] = Field(default=None, max_length=1000)
    type: Optional[str] = Field(default=None, max_length=50)


class BlogPostCreate(BaseModel):
    title: str
    slug: str
    excerpt: str
    content: str
    featured_image: Optional[str] = None
    category: str = "orthodontics"
    tags: List[str] = []
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: bool = False
    # Extended structured fields (article importer)
    seo_title: Optional[str] = None
    language: Optional[str] = "bg"
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: List[FaqItem] = []
    internal_links: List[LinkItem] = []
    external_sources: List[SourceItem] = []
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: List[str] = []
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogPostUpdate(BaseModel):
    title: Optional[str] = None
    slug: Optional[str] = None
    excerpt: Optional[str] = None
    content: Optional[str] = None
    featured_image: Optional[str] = None
    category: Optional[str] = None
    tags: Optional[List[str]] = None
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: Optional[bool] = None
    # Extended structured fields
    seo_title: Optional[str] = None
    language: Optional[str] = None
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: Optional[List[FaqItem]] = None
    internal_links: Optional[List[LinkItem]] = None
    external_sources: Optional[List[SourceItem]] = None
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: Optional[List[str]] = None
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogPost(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    slug: str
    excerpt: str
    content: str
    featured_image: Optional[str] = None
    category: str = "orthodontics"
    tags: List[str] = []
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: bool = False
    author_id: Optional[str] = None
    author_name: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    published_at: Optional[datetime] = None
    view_count: int = 0
    # Extended structured fields (added Feb 2026 with Article Importer)
    seo_title: Optional[str] = None
    language: Optional[str] = "bg"
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: List[FaqItem] = []
    internal_links: List[LinkItem] = []
    external_sources: List[SourceItem] = []
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: List[str] = []
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogViewEvent(BaseModel):
    post_slug: str
    visitor_id: str
    referrer: Optional[str] = None
    user_agent: Optional[str] = None


# ─── Analytics Models ──────────────────────────────────────

class AnalyticsEvent(BaseModel):
    # Defensive: Pydantic v2 default is `extra="ignore"` but we set it
    # explicitly so a future Pydantic config change can't silently start
    # accepting PII-looking keys (phone, email, patient_message, …).
    model_config = ConfigDict(extra="ignore")

    event_type: str
    session_id: str
    timestamp: str
    # Legacy quiz funnel fields ----------------------------------------
    question_id: Optional[str] = None
    question_index: Optional[int] = None
    answer: Optional[str] = None
    score: Optional[int] = None
    time_spent_ms: Optional[int] = None
    total_score: Optional[int] = None
    band: Optional[str] = None
    total_time_ms: Optional[int] = None
    answers: Optional[List[Dict[str, Any]]] = None
    choice: Optional[str] = None
    form_version: Optional[str] = None
    city: Optional[str] = None
    has_name: Optional[bool] = None
    has_email: Optional[bool] = None
    segment: Optional[str] = None
    flags: Optional[List[str]] = None
    # P6 patient-funnel fields (Feb 2026) ------------------------------
    # Strictly non-PII. Each is wired from frontend/lib/patientAnalytics.ts.
    lead_id: Optional[str] = None
    clinic_id: Optional[str] = None
    partner_tier: Optional[str] = None
    placement_label: Optional[str] = None
    source: Optional[str] = None
    rank_position: Optional[int] = None
    success: Optional[bool] = None
    error_code: Optional[str] = None
    reason: Optional[str] = None
    attempted_action: Optional[str] = None
    clinic_count: Optional[int] = None
    has_premium: Optional[bool] = None
    has_featured: Optional[bool] = None
    has_standard: Optional[bool] = None
    has_lead_id: Optional[bool] = None



# ─── Consultation Workflow Models (Feb 2026) ───────────────
# Separate from Lead. Lead = patient/source/quiz object.
# ConsultationRequest = clinic workflow object linked back to a lead.

CLINIC_STATUS_VALUES = (
    "evaluation_partner", "active_partner", "premium_partner",
    "probation", "waiting_list", "inactive",
)
SUBSCRIPTION_STATUS_VALUES = (
    "trial", "active", "past_due", "cancelled", "unpaid",
)
CONSULTATION_STATUS_VALUES = (
    "new", "assigned", "clinic_viewed", "call_attempted",
    "patient_contacted", "no_answer", "booked", "rescheduled",
    "patient_declined", "not_suitable", "attended", "no_show",
    "cancelled", "expired", "disputed",
    # P5 assisted-choice flow — admin-only triage queue. Rows with this
    # status carry `assigned_clinic_id=null` and `created_from="assisted_choice_flow"`
    # and are intentionally invisible to clinic-portal queries.
    "needs_zubite_review",
)
APPOINTMENT_STATUS_VALUES = (
    "booked", "confirmed", "rescheduled", "cancelled",
    "attended", "no_show",
)
APPOINTMENT_TYPE_VALUES = (
    "orthodontic_consultation", "invisalign_consultation",
    "braces_consultation", "implant_consultation",
    "cosmetic_consultation", "full_mouth_rehab_consultation",
    "general_consultation",
)
ACTION_TYPE_VALUES = (
    "mark_viewed", "call_attempted", "patient_contacted", "no_answer",
    "book_consultation", "reschedule", "patient_declined",
    "not_suitable", "mark_attended", "mark_no_show", "cancel",
    "admin_note",
)


class ClinicCreate(BaseModel):
    """Admin-side clinic creation. Mirrors the existing `clinics` collection
    fields and adds the new workflow/subscription fields."""
    model_config = ConfigDict(extra="ignore")
    clinic_name: str = Field(min_length=1, max_length=200)
    city: str = Field(min_length=1, max_length=100)
    email: EmailStr
    phone: str = Field(min_length=1, max_length=50)
    address: Optional[str] = Field(default=None, max_length=500)
    website: Optional[str] = Field(default=None, max_length=500)
    contact_person: Optional[str] = Field(default=None, max_length=200)
    treatments_offered: List[str] = []
    clinic_status: str = "evaluation_partner"
    subscription_status: str = "trial"
    monthly_plan: Optional[str] = Field(default=None, max_length=100)
    notification_email: Optional[EmailStr] = None


# ─── Admin Rich Clinic Profile Editor (R1, Feb 2026) ────────────────
# Nested admin-editable profile object stored as `clinic_profile` on the
# clinic doc. Public exposure is tier-gated and only ever surfaces fields
# when `profile_status == "published"`. Frontend mirror:
# frontend/app/admin/clinics/[id]/page.tsx + the public profile page.

PARTNER_TIER_VALUES = ("standard", "featured", "premium")
PROFILE_STATUS_VALUES = ("draft", "published")


class ClinicProfileCase(BaseModel):
    """A single text-only case in the case library. R1: no images,
    no patient PII. `published` requires `consent_confirmed=True`."""
    model_config = ConfigDict(extra="ignore")

    id: Optional[str] = Field(default=None, max_length=80)
    title: str = Field(min_length=1, max_length=120)
    category: str = Field(min_length=1, max_length=80)
    summary: str = Field(min_length=1, max_length=700)
    status: str = Field(default="draft")
    consent_confirmed: bool = False


class ClinicReviewSources(BaseModel):
    """Nested mirror of the flat top-level review fields. The flat
    fields remain canonical for `_build_review_signals` compatibility;
    this nested shape is what the admin editor reads/writes through
    the profile blob."""
    model_config = ConfigDict(extra="ignore")

    google_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    google_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    google_url: Optional[str] = Field(default=None, max_length=500)

    facebook_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    facebook_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    facebook_url: Optional[str] = Field(default=None, max_length=500)

    superdoc_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    superdoc_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    superdoc_url: Optional[str] = Field(default=None, max_length=500)


class ClinicProfile(BaseModel):
    """R1 rich-profile object. URL-only media (no upload).

    Tier gating happens at READ time in `_safe_clinic_payload`. Storage
    is tier-agnostic so that downgrades preserve data."""
    model_config = ConfigDict(extra="ignore")

    profile_status: str = Field(default="draft")

    short_description: Optional[str] = Field(default=None, max_length=500)
    patient_intro: Optional[str] = Field(default=None, max_length=500)
    treatment_focus: Optional[List[str]] = None

    hero_image_url: Optional[str] = Field(default=None, max_length=500)
    clinic_video_url: Optional[str] = Field(default=None, max_length=500)
    doctor_video_url: Optional[str] = Field(default=None, max_length=500)

    doctor_spotlight_name: Optional[str] = Field(default=None, max_length=200)
    doctor_spotlight_role: Optional[str] = Field(default=None, max_length=200)
    doctor_spotlight_bio: Optional[str] = Field(default=None, max_length=1000)
    team_note: Optional[str] = Field(default=None, max_length=500)

    clinic_story: Optional[str] = Field(default=None, max_length=1500)
    environment_description: Optional[str] = Field(default=None, max_length=1000)
    consultation_process: Optional[str] = Field(default=None, max_length=1000)

    review_sources: Optional[ClinicReviewSources] = None
    case_library: Optional[List[ClinicProfileCase]] = None

    updated_at: Optional[str] = None
    published_at: Optional[str] = None


class ClinicAdminUpdate(BaseModel):
    """Admin can patch any of these. All optional."""
    model_config = ConfigDict(extra="ignore")
    clinic_name: Optional[str] = Field(default=None, max_length=200)
    city: Optional[str] = Field(default=None, max_length=100)
    address: Optional[str] = Field(default=None, max_length=500)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    website: Optional[str] = Field(default=None, max_length=500)
    contact_person: Optional[str] = Field(default=None, max_length=200)
    treatments_offered: Optional[List[str]] = None
    clinic_status: Optional[str] = None
    subscription_status: Optional[str] = None
    monthly_plan: Optional[str] = Field(default=None, max_length=100)
    notification_email: Optional[EmailStr] = None
    description: Optional[str] = Field(default=None, max_length=2000)

    # ── Rich Profile Editor R1 ───────────────────────────────────────
    partner_tier: Optional[str] = None
    clinic_profile: Optional[ClinicProfile] = None

    # ── External review signals (display-only, admin-gated) ──────────
    # All fields are optional. Bounds match the publish gate in
    # `backend/routers/public.py::_build_review_signals`. The router is the
    # ultimate authority on whether a value is surfaced publicly; the
    # schema here only validates write-side admin input.
    google_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    google_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    google_place_url: Optional[str] = Field(default=None, max_length=500)
    facebook_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    facebook_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    facebook_page_url: Optional[str] = Field(default=None, max_length=500)
    superdoc_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    superdoc_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    superdoc_profile_url: Optional[str] = Field(default=None, max_length=500)
    review_sources_last_checked_at: Optional[datetime] = None
    review_sources_verified_by_admin: Optional[bool] = None


class ConsultationRequestCreate(BaseModel):
    """Admin creates a consultation request directly (rare — usually
    auto-created from a lead assign). Allows manual entry too."""
    model_config = ConfigDict(extra="ignore")
    patient_name: str = Field(min_length=1, max_length=200)
    patient_phone: str = Field(min_length=1, max_length=50)
    patient_email: Optional[EmailStr] = None
    patient_city: Optional[str] = Field(default=None, max_length=100)
    treatment_interest: str = Field(min_length=1, max_length=100)
    preferred_contact_time: Optional[str] = Field(default=None, max_length=200)
    urgency: Optional[str] = Field(default=None, max_length=50)
    readiness: Optional[str] = Field(default=None, max_length=50)
    quiz_result_id: Optional[str] = None
    lead_id: Optional[str] = None
    source: Optional[str] = Field(default=None, max_length=100)
    utm_source: Optional[str] = Field(default=None, max_length=300)
    utm_campaign: Optional[str] = Field(default=None, max_length=300)
    utm_adset: Optional[str] = Field(default=None, max_length=300)
    utm_ad: Optional[str] = Field(default=None, max_length=300)
    assigned_clinic_id: Optional[str] = None


class ConsultationAssignClinic(BaseModel):
    clinic_id: str = Field(min_length=1, max_length=100)


class ConsultationAdminPatch(BaseModel):
    model_config = ConfigDict(extra="ignore")
    status: Optional[str] = None
    notes: Optional[str] = Field(default=None, max_length=5000)


class AppointmentDetails(BaseModel):
    """Embedded payload when clinic books or reschedules a consultation."""
    appointment_type: str
    start_time: str  # ISO 8601
    end_time: str  # ISO 8601
    notes: Optional[str] = Field(default=None, max_length=2000)


class ConsultationActionRequest(BaseModel):
    """Body for /api/clinic/consultation-requests/{id}/action."""
    action_type: str
    note: Optional[str] = Field(default=None, max_length=2000)
    appointment: Optional[AppointmentDetails] = None


class ClinicAppointmentCreate(BaseModel):
    """Direct calendar entry (clinic creates an appointment without a request).
    Rare — usually appointments are created via the action endpoint."""
    model_config = ConfigDict(extra="ignore")
    consultation_request_id: Optional[str] = None
    patient_name: str = Field(min_length=1, max_length=200)
    patient_phone: str = Field(min_length=1, max_length=50)
    treatment_category: Optional[str] = Field(default=None, max_length=100)
    appointment_type: str
    start_time: str
    end_time: str
    notes: Optional[str] = Field(default=None, max_length=2000)


class ClinicAppointmentPatch(BaseModel):
    model_config = ConfigDict(extra="ignore")
    appointment_type: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    status: Optional[str] = None
    notes: Optional[str] = Field(default=None, max_length=2000)
