from pydantic import BaseModel, Field, ConfigDict, EmailStr, field_validator
from typing import List, Optional, Dict, Any, Literal
from datetime import datetime, timezone
import uuid


# ─── Public / Seed Models ─────────────────────────────────

class Clinic(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    city_slug: str
    city_name: str
    treatments_supported: List[str] = []
    is_active: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class LeadCreate(BaseModel):
    """Lead create payload. Accepts but does not require the full attribution
    payload generated by `frontend/lib/attribution.ts`. Attribution fields are
    optional — old/legacy submissions still work."""
    model_config = ConfigDict(extra="ignore")
    city_slug: str = Field(min_length=1, max_length=50)
    treatment_type: str = Field(min_length=1, max_length=50)
    answers: Dict[str, Any] = {}
    can_travel: bool = True
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    consent: bool = False
    source: Optional[str] = Field(default=None, max_length=100)
    utm_source: Optional[str] = Field(default=None, max_length=200)
    utm_campaign: Optional[str] = Field(default=None, max_length=200)
    utm_adset: Optional[str] = Field(default=None, max_length=200)
    utm_ad: Optional[str] = Field(default=None, max_length=200)
    page_path: Optional[str] = Field(default=None, max_length=500)

    # Coerce empty / whitespace-only strings to None BEFORE Pydantic
    # tries to validate them as `EmailStr`. Frontend lead-capture forms
    # (MasterQuiz, TreatmentQuiz, AlignersVsBracesQuiz, the per-city /
    # treatment quiz, LeadCaptureForm) all default the email input to
    # `""` and currently submit that empty string when the patient
    # leaves the field blank — `EmailStr` would otherwise reject it
    # with HTTP 422 and break the entire onboarding.
    @field_validator("email", "name", "phone", mode="before")
    @classmethod
    def _coerce_blank_string_to_none(cls, v):
        if isinstance(v, str) and not v.strip():
            return None
        return v

    # ─── First-touch attribution (immutable) ────────────────────────
    first_utm_source: Optional[str] = Field(default=None, max_length=300)
    first_utm_medium: Optional[str] = Field(default=None, max_length=200)
    first_utm_campaign: Optional[str] = Field(default=None, max_length=300)
    first_utm_adset: Optional[str] = Field(default=None, max_length=300)
    first_utm_ad: Optional[str] = Field(default=None, max_length=300)
    first_utm_campaign_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_adset_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_ad_id: Optional[str] = Field(default=None, max_length=100)
    first_utm_content: Optional[str] = Field(default=None, max_length=300)
    first_utm_term: Optional[str] = Field(default=None, max_length=300)
    first_fbclid: Optional[str] = Field(default=None, max_length=300)
    first_gclid: Optional[str] = Field(default=None, max_length=300)
    first_msclkid: Optional[str] = Field(default=None, max_length=300)
    first_ttclid: Optional[str] = Field(default=None, max_length=300)
    first_landing_page: Optional[str] = Field(default=None, max_length=1000)
    first_landing_page_type: Optional[str] = Field(default=None, max_length=50)
    first_referrer: Optional[str] = Field(default=None, max_length=1000)
    first_lead_source_type: Optional[str] = Field(default=None, max_length=50)
    first_article_slug: Optional[str] = Field(default=None, max_length=300)
    first_article_title: Optional[str] = Field(default=None, max_length=500)
    first_seen_at: Optional[str] = Field(default=None, max_length=50)
    original_lead_source_type: Optional[str] = Field(default=None, max_length=50)

    # ─── Latest-touch attribution ────────────────────────
    latest_utm_source: Optional[str] = Field(default=None, max_length=300)
    latest_utm_medium: Optional[str] = Field(default=None, max_length=200)
    latest_utm_campaign: Optional[str] = Field(default=None, max_length=300)
    latest_utm_adset: Optional[str] = Field(default=None, max_length=300)
    latest_utm_ad: Optional[str] = Field(default=None, max_length=300)
    latest_utm_campaign_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_adset_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_ad_id: Optional[str] = Field(default=None, max_length=100)
    latest_utm_content: Optional[str] = Field(default=None, max_length=300)
    latest_utm_term: Optional[str] = Field(default=None, max_length=300)
    latest_fbclid: Optional[str] = Field(default=None, max_length=300)
    latest_gclid: Optional[str] = Field(default=None, max_length=300)
    latest_msclkid: Optional[str] = Field(default=None, max_length=300)
    latest_ttclid: Optional[str] = Field(default=None, max_length=300)
    latest_landing_page: Optional[str] = Field(default=None, max_length=1000)
    latest_landing_page_type: Optional[str] = Field(default=None, max_length=50)
    latest_referrer: Optional[str] = Field(default=None, max_length=1000)
    latest_lead_source_type: Optional[str] = Field(default=None, max_length=50)
    latest_article_slug: Optional[str] = Field(default=None, max_length=300)
    latest_article_title: Optional[str] = Field(default=None, max_length=500)
    last_seen_at: Optional[str] = Field(default=None, max_length=50)

    # ─── Conversion data ────────────────────────
    content_path_before_conversion: Optional[List[Dict[str, Any]]] = None
    pages_viewed_before_conversion: Optional[int] = None
    blog_assisted_conversion: Optional[bool] = None
    internal_content_assisted_conversion: Optional[bool] = None
    conversion_page: Optional[str] = Field(default=None, max_length=1000)
    submitted_at: Optional[str] = Field(default=None, max_length=50)
    time_to_submit_seconds: Optional[int] = None


class LeadContactUpdate(BaseModel):
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    consent: bool = False


# ─── Patient layer P4: request-call ───────────────────────────────
# Body for POST /api/leads/{lead_id}/request-call. The endpoint enforces
# `consent_to_share=True` and that `clinic_id` belongs to the lead's
# recommended set. Phone validation is intentionally permissive (digit
# count check + optional `+` prefix) — matches existing platform rules
# for `LeadContactUpdate` while preventing empty / placeholder input.
RequestCallSource = Literal["matching_card", "clinic_profile"]


class RequestCallBody(BaseModel):
    model_config = ConfigDict(extra="ignore")
    clinic_id: str = Field(min_length=1, max_length=200)
    phone: str = Field(min_length=4, max_length=50)
    consent_to_share: bool
    source: RequestCallSource = "matching_card"


# ─── Patient layer P5: assisted choice ────────────────────────────
AssistedChoiceSource = Literal["matching_page", "clinic_profile"]


class RequestZubiteHelpBody(BaseModel):
    """`POST /api/leads/{lead_id}/request-zubite-help` payload.
    Mutual exclusion with `RequestCallBody` is enforced server-side."""
    model_config = ConfigDict(extra="ignore")
    phone: str = Field(min_length=4, max_length=50)
    consent_to_share: bool
    # Optional free-text note. Bounded length to keep DB rows compact
    # and prevent abuse; PII redaction is admin's responsibility.
    message: Optional[str] = Field(default=None, max_length=1000)
    source: AssistedChoiceSource = "matching_page"


# ─── Patient layer: Save Care Pass by email ────────────────────────
# Body for POST /api/leads/{lead_id}/email-care-pass.
# Sends the patient a summary of their quiz outcome + the Manual
# Recommendation Mode explanation + Care Pass eligibility text.
# Strictly NO instant-clinic-match / booking promises in the email.
class SaveCarePassEmailBody(BaseModel):
    model_config = ConfigDict(extra="ignore")
    email: EmailStr
    consent_to_email: bool
    # Optional display name to personalise the greeting.
    name: Optional[str] = Field(default=None, max_length=200)


class QuickChatLeadCreate(BaseModel):
    """Bootstraps a minimal, quiz-less lead so a patient who lands on a
    clinic's public profile without ever taking the quiz can still start
    a chat — the name is the only thing the clinic needs to call them."""
    model_config = ConfigDict(extra="ignore")
    name: str = Field(min_length=1, max_length=120)


# ─── MVP unlock-mechanic (June 2026, Phase B) ────────────────────
# Body for POST /api/leads/{lead_id}/unlock-result.
#
# Defensive lead-capture gate for any lead that was created WITHOUT
# contact details (e.g. anonymous quiz path or a future split between
# quiz answers and contact collection). Existing quiz POSTs already
# include name/phone/email/consent, so this endpoint is idempotent —
# if the lead already has contacts, we simply re-confirm the unlock
# flags without overwriting the original values.
class UnlockResultBody(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str = Field(min_length=1, max_length=200)
    phone: str = Field(min_length=4, max_length=50)
    email: EmailStr
    consent: bool
    consultation_type: Optional[str] = Field(default=None, max_length=40)


class Lead(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    city_slug: str
    treatment_type: str
    score_total: int = 0
    band: str = "RED"
    status: str = "NEW"
    assigned_clinic_id: Optional[str] = None
    # Общност OTP patient account that owns this lead (see `patients`
    # collection / patient_auth.py) — distinct from `patient_number` below,
    # which is a clinic-facing sequential display id. Never accepted from
    # the client; only ever set server-side via create_lead's auth
    # dependency, the OTP-verify retroactive link, or POST /leads/{id}/claim.
    patient_id: Optional[str] = None
    name: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    consent: bool = False
    answers: Dict[str, Any] = {}
    score_breakdown: Dict[str, int] = {}
    can_travel: bool = True
    utm_source: Optional[str] = None
    utm_campaign: Optional[str] = None
    utm_adset: Optional[str] = None
    utm_ad: Optional[str] = None
    page_path: Optional[str] = None
    notes: Optional[str] = None
    # ─── Attribution (Feb 2026) — see /app/frontend/lib/attribution.ts ───
    # First-touch
    first_utm_source: Optional[str] = None
    first_utm_medium: Optional[str] = None
    first_utm_campaign: Optional[str] = None
    first_utm_adset: Optional[str] = None
    first_utm_ad: Optional[str] = None
    first_utm_campaign_id: Optional[str] = None
    first_utm_adset_id: Optional[str] = None
    first_utm_ad_id: Optional[str] = None
    first_utm_content: Optional[str] = None
    first_utm_term: Optional[str] = None
    first_fbclid: Optional[str] = None
    first_gclid: Optional[str] = None
    first_msclkid: Optional[str] = None
    first_ttclid: Optional[str] = None
    first_landing_page: Optional[str] = None
    first_landing_page_type: Optional[str] = None
    first_referrer: Optional[str] = None
    first_lead_source_type: Optional[str] = None
    first_article_slug: Optional[str] = None
    first_article_title: Optional[str] = None
    first_seen_at: Optional[str] = None
    original_lead_source_type: Optional[str] = None
    # Latest-touch
    latest_utm_source: Optional[str] = None
    latest_utm_medium: Optional[str] = None
    latest_utm_campaign: Optional[str] = None
    latest_utm_adset: Optional[str] = None
    latest_utm_ad: Optional[str] = None
    latest_utm_campaign_id: Optional[str] = None
    latest_utm_adset_id: Optional[str] = None
    latest_utm_ad_id: Optional[str] = None
    latest_utm_content: Optional[str] = None
    latest_utm_term: Optional[str] = None
    latest_fbclid: Optional[str] = None
    latest_gclid: Optional[str] = None
    latest_msclkid: Optional[str] = None
    latest_ttclid: Optional[str] = None
    latest_landing_page: Optional[str] = None
    latest_landing_page_type: Optional[str] = None
    latest_referrer: Optional[str] = None
    latest_lead_source_type: Optional[str] = None
    latest_article_slug: Optional[str] = None
    latest_article_title: Optional[str] = None
    last_seen_at: Optional[str] = None
    # Conversion data
    content_path_before_conversion: Optional[List[Dict[str, Any]]] = None
    pages_viewed_before_conversion: Optional[int] = None
    blog_assisted_conversion: Optional[bool] = None
    internal_content_assisted_conversion: Optional[bool] = None
    conversion_page: Optional[str] = None
    submitted_at: Optional[str] = None
    time_to_submit_seconds: Optional[int] = None
    # ─── Soft duplicate detection (Phase 2C) ────────────────────
    # Non-blocking flag: a new lead is always created; admins use these
    # fields to triage. Never exposed in public or clinic endpoints.
    is_potential_duplicate: bool = False
    duplicate_reason: Optional[str] = None
    possible_duplicate_lead_id: Optional[str] = None

    # ─── MVP unlock-mechanic foundation (June 2026, Phase A) ────
    # These fields gate the full result + Care Pass behind a clinic-
    # confirmed consultation. See lead-flow doc + emails.py.
    #
    # State machine (canonical):
    #   1. Lead created (no contact)   → all False
    #   2. Contact details submitted   → contact_details_submitted=True,
    #                                    full_result_unlocked=True,
    #                                    care_pass_eligible=True
    #   3. Consultation requested      → consultation_booked_through_zubite=True
    #                                    (set when patient submits a
    #                                    booking/request via Zubite.bg)
    #   4. Clinic confirms it          → clinic_confirmed_consultation=True
    #                                    care_pass_unlocked=True
    #
    # Care Pass UNLOCK rule (single source of truth):
    #   care_pass_unlocked := contact_details_submitted
    #                       AND consultation_booked_through_zubite
    #                       AND clinic_confirmed_consultation
    #
    # `consultation_type` records WHICH path confirmed Care Pass so we
    # can attribute future analytics cleanly.
    contact_details_submitted: bool = False
    full_result_unlocked: bool = False
    care_pass_eligible: bool = False
    care_pass_unlocked: bool = False
    consultation_booked_through_zubite: bool = False
    clinic_confirmed_consultation: bool = False
    clinic_confirmed_consultation_at: Optional[str] = None
    consultation_type: Optional[str] = None   # online_orientation | offline_in_person | request_call
    # 90-day no-show block — used by future online-orientation eligibility checks.
    patient_free_orientation_blocked_until: Optional[str] = None
    # Audit trail for the explicit "unlock" event.
    contact_details_submitted_at: Optional[str] = None

    # ─── Clinic "Пациенти" section (global numeric patient ID) ──
    # patient_number is a stable, platform-wide unique identifier assigned
    # lazily the first time any clinic's patients list is loaded for a lead
    # that has an assigned_clinic_id. See routers/clinic_patients.py.
    patient_number: Optional[int] = None
    patient_number_assigned_at: Optional[str] = None
    # Free-text note the owning clinic keeps on this patient. Cleared on
    # clinic reassignment (routers/admin.py admin_update_lead) so it never
    # leaks to a different clinic.
    clinic_internal_note: Optional[str] = None
    clinic_internal_note_updated_at: Optional[str] = None


# ─── Admin Models ──────────────────────────────────────────

class LeadStatusUpdate(BaseModel):
    status: Optional[str] = None
    assigned_clinic_id: Optional[str] = None
    notes: Optional[str] = None

    @field_validator("status")
    @classmethod
    def _validate_status(cls, v: Optional[str]) -> Optional[str]:
        return _validate_lead_status(v)


class LeadUpdate(BaseModel):
    name: Optional[str] = Field(default=None, max_length=200)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    city_slug: Optional[str] = Field(default=None, max_length=50)
    status: Optional[str] = Field(default=None, max_length=50)
    notes: Optional[str] = Field(default=None, max_length=5000)

    @field_validator("status")
    @classmethod
    def _validate_status(cls, v: Optional[str]) -> Optional[str]:
        return _validate_lead_status(v)


class ClinicPatientNoteUpdate(BaseModel):
    """Body for PUT /api/clinic/patients/{patient_number}/note — a full
    replace of the clinic's free-text internal note on that patient."""
    note: str = Field(max_length=5000)


# ─── Lead status allow-list (Phase 2A) ────────────────────────────
# Backward-compatible: existing DB only contains NEW and CONTACTED.
# Reject anything outside this set with a 422 from Pydantic.
LEAD_STATUS_ALLOWED = frozenset({"NEW", "CONTACTED", "SCHEDULED", "COMPLETED", "CANCELLED"})


def _validate_lead_status(v: Optional[str]) -> Optional[str]:
    if v is None:
        return v
    if not isinstance(v, str):
        raise ValueError("status must be a string")
    if v not in LEAD_STATUS_ALLOWED:
        raise ValueError(
            f"status must be one of {sorted(LEAD_STATUS_ALLOWED)}; got '{v}'"
        )
    return v


class AdminLogin(BaseModel):
    username: str = Field(min_length=1, max_length=200)
    password: str = Field(min_length=1, max_length=200)


class AdminUser(BaseModel):
    id: str
    username: str
    role: str = "admin"


class TokenResponse(BaseModel):
    # access_token + token_type are only populated when AUTH_REQUIRE_COOKIE=0
    # (Bearer/cookie compatibility mode). In cookie-only mode they are omitted
    # entirely from the response body — the JWT lives in the httpOnly cookie.
    access_token: Optional[str] = None
    token_type: Optional[str] = None
    user: AdminUser


# ─── Clinic Models ─────────────────────────────────────────

class ClinicLogin(BaseModel):
    email: EmailStr
    password: str = Field(min_length=1, max_length=200)


class ClinicUserOut(BaseModel):
    id: str
    clinic_name: str
    city: str
    email: str
    phone: str
    status: str
    address: Optional[str] = None
    website: Optional[str] = None
    company_name: Optional[str] = None
    eik: Optional[str] = None
    mol: Optional[str] = None
    description: Optional[str] = None
    # Viber deep-link channel. `viber_phone` is stored already normalised
    # to E.164 (see phone_utils) because a deep link cannot carry the
    # free-text formats the rest of the platform accepts.
    viber_enabled: bool = False
    viber_phone: Optional[str] = None
    # Co-branding for clinic-facing exports (the review poster). Resolved
    # from logo_file_id server-side — never stored/returned as a raw path.
    logo_url: Optional[str] = None


class ClinicTokenResponse(BaseModel):
    # Same semantics as `TokenResponse` — populated only when
    # AUTH_REQUIRE_COOKIE=0.
    access_token: Optional[str] = None
    token_type: Optional[str] = None
    user: ClinicUserOut


class ClinicProfileUpdate(BaseModel):
    clinic_name: Optional[str] = None
    phone: Optional[str] = None
    city: Optional[str] = None
    address: Optional[str] = None
    website: Optional[str] = None
    company_name: Optional[str] = None
    eik: Optional[str] = None
    mol: Optional[str] = None
    description: Optional[str] = None
    viber_enabled: Optional[bool] = None
    # Free-text on the way in; the endpoint normalises to E.164 before
    # storing and rejects anything it cannot resolve.
    viber_phone: Optional[str] = Field(default=None, max_length=40)


class ClinicPasswordChange(BaseModel):
    current_password: str = Field(min_length=1, max_length=200)
    new_password: str = Field(min_length=8, max_length=200)


class ClinicLeadStatusUpdate(BaseModel):
    status: str


# ─── Phase 2B — Destructive endpoint confirmation bodies ─────────
# Each destructive admin endpoint requires a fixed confirmation phrase to
# guard against accidental fat-finger curl/UI calls.
RESET_ANALYTICS_TOKEN = "CONFIRM_RESET_ANALYTICS"
RESET_BLOG_VIEWS_TOKEN = "CONFIRM_RESET_BLOG_VIEWS"
CLEANUP_LEADS_TOKEN = "CONFIRM_DELETE_NON_MATCHING_LEADS"


class ConfirmationBody(BaseModel):
    """Body shared by reset-analytics / reset-blog-views."""
    confirmation_token: str = Field(min_length=1, max_length=200)


class CleanupLeadsBody(BaseModel):
    """Body for the cleanup-leads endpoint. Requires:
      - explicit non-empty keep_ids
      - explicit confirmation phrase
      - force=True if the operation would delete >50% of the leads
    """
    confirmation_token: str = Field(min_length=1, max_length=200)
    keep_ids: List[str] = Field(min_length=1)
    force: bool = False

    @field_validator("keep_ids")
    @classmethod
    def _no_empty_ids(cls, v: List[str]) -> List[str]:
        cleaned = [s for s in v if isinstance(s, str) and s.strip()]
        if not cleaned:
            raise ValueError("keep_ids must be a non-empty list of strings")
        return cleaned


class ClinicApplicationCreate(BaseModel):
    clinic_name: str = Field(min_length=2, max_length=200)
    city: str = Field(min_length=2, max_length=100)
    address: str = Field(min_length=2, max_length=500)
    website: Optional[str] = Field(default=None, max_length=500)
    contact_name: str = Field(min_length=2, max_length=200)
    phone: str = Field(min_length=5, max_length=50)
    email: EmailStr
    offers_aligners: bool = False
    offers_braces: bool = False
    offers_implants: bool = False
    treats_adults: bool = False
    treats_children: bool = False
    years_experience: Optional[int] = Field(default=None, ge=0, le=100)
    number_of_cases_per_month: Optional[str] = Field(default=None, max_length=100)
    do_you_use_digital_scans: Optional[bool] = None
    what_types_of_patients_are_best_for_you: Optional[str] = Field(default=None, max_length=2000)
    average_response_time: Optional[str] = Field(default=None, max_length=100)


# ─── Blog Models ───────────────────────────────────────────

class FaqItem(BaseModel):
    q: str = Field(min_length=1, max_length=500)
    a: str = Field(min_length=1, max_length=5000)


class LinkItem(BaseModel):
    label: str = Field(min_length=1, max_length=200)
    url: str = Field(min_length=1, max_length=1000)


class SourceItem(BaseModel):
    title: str = Field(min_length=1, max_length=300)
    url: str = Field(min_length=1, max_length=1000)


class CtaBlock(BaseModel):
    title: Optional[str] = Field(default=None, max_length=300)
    text: Optional[str] = Field(default=None, max_length=2000)
    button: Optional[str] = Field(default=None, max_length=200)
    url: Optional[str] = Field(default=None, max_length=1000)
    type: Optional[str] = Field(default=None, max_length=50)


class BlogPostCreate(BaseModel):
    title: str
    slug: str
    excerpt: str
    content: str
    featured_image: Optional[str] = None
    category: str = "orthodontics"
    tags: List[str] = []
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: bool = False
    # Extended structured fields (article importer)
    seo_title: Optional[str] = None
    language: Optional[str] = "bg"
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: List[FaqItem] = []
    internal_links: List[LinkItem] = []
    external_sources: List[SourceItem] = []
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: List[str] = []
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogPostUpdate(BaseModel):
    title: Optional[str] = None
    slug: Optional[str] = None
    excerpt: Optional[str] = None
    content: Optional[str] = None
    featured_image: Optional[str] = None
    category: Optional[str] = None
    tags: Optional[List[str]] = None
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: Optional[bool] = None
    # Extended structured fields
    seo_title: Optional[str] = None
    language: Optional[str] = None
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: Optional[List[FaqItem]] = None
    internal_links: Optional[List[LinkItem]] = None
    external_sources: Optional[List[SourceItem]] = None
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: Optional[List[str]] = None
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogPost(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    slug: str
    excerpt: str
    content: str
    featured_image: Optional[str] = None
    category: str = "orthodontics"
    tags: List[str] = []
    meta_title: Optional[str] = None
    meta_description: Optional[str] = None
    is_published: bool = False
    author_id: Optional[str] = None
    author_name: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    published_at: Optional[datetime] = None
    view_count: int = 0
    # Extended structured fields (added Feb 2026 with Article Importer)
    seo_title: Optional[str] = None
    language: Optional[str] = "bg"
    reviewed_by: Optional[str] = None
    last_reviewed: Optional[str] = None
    content_html: Optional[str] = None
    faq: List[FaqItem] = []
    internal_links: List[LinkItem] = []
    external_sources: List[SourceItem] = []
    cta: Optional[CtaBlock] = None
    featured_image_alt: Optional[str] = None
    image_alt_texts: List[str] = []
    faq_schema: Optional[Dict[str, Any]] = None
    article_schema: Optional[Dict[str, Any]] = None


class BlogViewEvent(BaseModel):
    post_slug: str
    visitor_id: str
    referrer: Optional[str] = None
    user_agent: Optional[str] = None


# ─── Analytics Models ──────────────────────────────────────

class AnalyticsEvent(BaseModel):
    # Defensive: Pydantic v2 default is `extra="ignore"` but we set it
    # explicitly so a future Pydantic config change can't silently start
    # accepting PII-looking keys (phone, email, patient_message, …).
    model_config = ConfigDict(extra="ignore")

    event_type: str
    session_id: str
    timestamp: str
    # Legacy quiz funnel fields ----------------------------------------
    question_id: Optional[str] = None
    question_index: Optional[int] = None
    answer: Optional[str] = None
    score: Optional[int] = None
    time_spent_ms: Optional[int] = None
    total_score: Optional[int] = None
    band: Optional[str] = None
    total_time_ms: Optional[int] = None
    answers: Optional[List[Dict[str, Any]]] = None
    choice: Optional[str] = None
    form_version: Optional[str] = None
    city: Optional[str] = None
    has_name: Optional[bool] = None
    has_email: Optional[bool] = None
    segment: Optional[str] = None
    flags: Optional[List[str]] = None
    # P6 patient-funnel fields (Feb 2026) ------------------------------
    # Strictly non-PII. Each is wired from frontend/lib/patientAnalytics.ts.
    lead_id: Optional[str] = None
    clinic_id: Optional[str] = None
    partner_tier: Optional[str] = None
    placement_label: Optional[str] = None
    source: Optional[str] = None
    rank_position: Optional[int] = None
    success: Optional[bool] = None
    error_code: Optional[str] = None
    reason: Optional[str] = None
    attempted_action: Optional[str] = None
    clinic_count: Optional[int] = None
    has_premium: Optional[bool] = None
    has_featured: Optional[bool] = None
    has_standard: Optional[bool] = None
    has_lead_id: Optional[bool] = None



# ─── Consultation Workflow Models (Feb 2026) ───────────────
# Separate from Lead. Lead = patient/source/quiz object.
# ConsultationRequest = clinic workflow object linked back to a lead.

CLINIC_STATUS_VALUES = (
    "evaluation_partner", "active_partner", "premium_partner",
    "probation", "waiting_list", "inactive",
)
SUBSCRIPTION_STATUS_VALUES = (
    "trial", "active", "past_due", "cancelled", "unpaid",
)
CONSULTATION_STATUS_VALUES = (
    "new", "assigned", "clinic_viewed", "call_attempted",
    "patient_contacted", "no_answer", "booked", "rescheduled",
    "patient_declined", "not_suitable", "attended", "no_show",
    "cancelled", "expired", "disputed",
    # P5 assisted-choice flow — admin-only triage queue. Rows with this
    # status carry `assigned_clinic_id=null` and `created_from="assisted_choice_flow"`
    # and are intentionally invisible to clinic-portal queries.
    "needs_zubite_review",
)
APPOINTMENT_STATUS_VALUES = (
    "booked", "confirmed", "rescheduled", "cancelled",
    "attended", "no_show",
)
APPOINTMENT_TYPE_VALUES = (
    "orthodontic_consultation", "invisalign_consultation",
    "braces_consultation", "implant_consultation",
    "cosmetic_consultation", "full_mouth_rehab_consultation",
    "general_consultation",
)
ACTION_TYPE_VALUES = (
    "mark_viewed", "call_attempted", "patient_contacted", "no_answer",
    "book_consultation", "reschedule", "patient_declined",
    "not_suitable", "mark_attended", "mark_no_show", "cancel",
    "admin_note",
)


class ClinicCreate(BaseModel):
    """Admin-side clinic creation. Mirrors the existing `clinics` collection
    fields and adds the new workflow/subscription fields."""
    model_config = ConfigDict(extra="ignore")
    clinic_name: str = Field(min_length=1, max_length=200)
    city: str = Field(min_length=1, max_length=100)
    email: EmailStr
    phone: str = Field(min_length=1, max_length=50)
    address: Optional[str] = Field(default=None, max_length=500)
    website: Optional[str] = Field(default=None, max_length=500)
    contact_person: Optional[str] = Field(default=None, max_length=200)
    treatments_offered: List[str] = []
    # Canonical going forward (Feb 2026 cleanup). When provided, takes
    # precedence over `treatments_offered`; when only the legacy field
    # is provided, the router copies its value here on insert.
    treatments_supported: List[str] = []
    clinic_status: str = "evaluation_partner"
    subscription_status: str = "trial"
    monthly_plan: Optional[str] = Field(default=None, max_length=100)
    notification_email: Optional[EmailStr] = None
    # Aligner brand/provider tags — validated by `aligner_brands.normalize_aligner_brand_entries`.
    aligner_brands_supported: Optional[List[Dict[str, Any]]] = None

    # ─── Feb 2026 pricing revamp ───────────────────────────────
    # `base_package` is the canonical public commercial layer.
    # Legacy `partner_tier` remains for audit but is no longer the
    # source of truth for public labels / entitlements.
    base_package: Optional[str] = None            # verified_profile | growth_partner
    founding_status: Optional[str] = None         # none | founding_growth | strategic_private
    billing_status: Optional[str] = None          # trial | active | past_due | paused | cancelled
    billing_cadence: Optional[str] = None         # yearly | custom_private
    monthly_price_eur: Optional[float] = None
    annual_price_eur: Optional[float] = None
    onboarding_fee_eur: Optional[float] = None
    founding_start_date: Optional[str] = None     # ISO date (yyyy-mm-dd)
    founding_end_date: Optional[str] = None       # ISO date (yyyy-mm-dd)
    private_terms_notes: Optional[str] = Field(default=None, max_length=2000)
    legacy_tier: Optional[str] = None             # populated on migration only
    # Public exposure of strategic_private status — never true unless
    # explicitly approved by admin.
    strategic_public_display: bool = False


# ─── Admin Rich Clinic Profile Editor (R1, Feb 2026) ────────────────
# Nested admin-editable profile object stored as `clinic_profile` on the
# clinic doc. Public exposure is tier-gated and only ever surfaces fields
# when `profile_status == "published"`. Frontend mirror:
# frontend/app/admin/clinics/[id]/page.tsx + the public profile page.

PARTNER_TIER_VALUES = ("standard", "featured", "premium")
PROFILE_STATUS_VALUES = ("draft", "published")


class ClinicProfileCase(BaseModel):
    """A single case in the case library.

    Feb 2026 revamp: supports treatment metadata (type, duration, price
    range as free text, materials, specifics) and before/after images
    (up to 3 each). Published cases still require `consent_confirmed=True`.
    NEVER include patient PII in any field.
    """
    model_config = ConfigDict(extra="ignore")

    id: Optional[str] = Field(default=None, max_length=80)
    title: str = Field(min_length=1, max_length=120)
    category: str = Field(min_length=1, max_length=80)
    summary: str = Field(min_length=1, max_length=700)
    status: str = Field(default="draft")
    consent_confirmed: bool = False

    # ── Revamp fields (Feb 2026) ────────────────────────────────
    treatment_type: Optional[str] = Field(default=None, max_length=80)
    # Free text — e.g. "6 месеца", "3 сесии", "1 година"
    duration: Optional[str] = Field(default=None, max_length=80)
    # Free text — per product decision the price is admin-authored copy,
    # e.g. "От 4 500 лв.", "По запитване", "3 200 – 4 000 лв."
    price: Optional[str] = Field(default=None, max_length=120)
    # Free text — e.g. "Invisalign Comprehensive, композитни фасети"
    materials: Optional[str] = Field(default=None, max_length=300)
    # Free text — clinical specifics / особености, no PII
    specifics: Optional[str] = Field(default=None, max_length=700)
    # Image URLs (served via `/api/files/{id}` or absolute). Max 3 each.
    before_images: Optional[List[str]] = None
    after_images: Optional[List[str]] = None


class ClinicProfileQA(BaseModel):
    """A single Q&A pair (Expert Q&A or FAQ module). Both modules share
    the shape so admin tooling and frontend rendering stays uniform."""
    model_config = ConfigDict(extra="ignore")

    question: str = Field(min_length=1, max_length=300)
    answer: str = Field(min_length=1, max_length=1500)


class ClinicProfilePriceRange(BaseModel):
    """Honest price range. `price_from` / `price_to` are inclusive bounds
    in the same currency. The optional `note` is intentionally non-binding
    ("ориентировъчно", "след преглед", etc.) so we never imply a
    contractual price."""
    model_config = ConfigDict(extra="ignore")

    treatment: str = Field(min_length=1, max_length=80)
    price_from: Optional[float] = Field(default=None, ge=0)
    price_to: Optional[float] = Field(default=None, ge=0)
    currency: str = Field(default="BGN", min_length=3, max_length=4)
    note: Optional[str] = Field(default=None, max_length=300)


class ClinicProfileTreatmentDetail(BaseModel):
    """Per-treatment expanded copy. Lives in `treatment_details[slug]`.
    All fields optional so admin can fill incrementally."""
    model_config = ConfigDict(extra="ignore")

    who_for: Optional[str] = Field(default=None, max_length=500)
    remote_start_possible: Optional[bool] = None
    note: Optional[str] = Field(default=None, max_length=500)


class ClinicProfileTreatmentCaseCount(BaseModel):
    """Clinic-declared completed-case total for one treatment.

    These totals are separate from ``case_library``: the latter contains a
    small set of consented, publishable examples, while this model records
    aggregate experience supplied by the clinic. The public UI labels the
    source explicitly and never presents it as independently verified.
    """
    model_config = ConfigDict(extra="ignore")

    treatment: str = Field(min_length=1, max_length=80)
    completed_cases: int = Field(ge=1, le=1_000_000)
    as_of_year: Optional[int] = Field(
        default=None,
        ge=2000,
        le=datetime.now(timezone.utc).year,
    )


class ClinicReviewSources(BaseModel):
    """Nested mirror of the flat top-level review fields. The flat
    fields remain canonical for `_build_review_signals` compatibility;
    this nested shape is what the admin editor reads/writes through
    the profile blob."""
    model_config = ConfigDict(extra="ignore")

    google_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    google_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    google_url: Optional[str] = Field(default=None, max_length=500)

    facebook_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    facebook_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    facebook_url: Optional[str] = Field(default=None, max_length=500)

    superdoc_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    superdoc_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    superdoc_url: Optional[str] = Field(default=None, max_length=500)


class ClinicProfile(BaseModel):
    """R1 rich-profile object. URL-only media (no upload).

    Tier gating happens at READ time in `_safe_clinic_payload`. Storage
    is tier-agnostic so that downgrades preserve data."""
    model_config = ConfigDict(extra="ignore")

    profile_status: str = Field(default="draft")

    short_description: Optional[str] = Field(default=None, max_length=500)
    patient_intro: Optional[str] = Field(default=None, max_length=500)
    founded_year: Optional[int] = Field(
        default=None,
        ge=1900,
        le=datetime.now(timezone.utc).year,
    )
    treatment_focus: Optional[List[str]] = None
    treatment_case_counts: Optional[List[ClinicProfileTreatmentCaseCount]] = None

    hero_image_url: Optional[str] = Field(default=None, max_length=500)
    clinic_video_url: Optional[str] = Field(default=None, max_length=500)
    doctor_video_url: Optional[str] = Field(default=None, max_length=500)

    # ── Feb 2026 — section-specific image uploads. Admins upload
    # via `/api/admin/upload` (jpeg/png/webp, ≤5MB) and the returned
    # URL is persisted here. Each is rendered in its corresponding
    # profile section on the public clinic page when present.
    doctor_spotlight_image_url: Optional[str] = Field(default=None, max_length=500)
    team_image_url: Optional[str] = Field(default=None, max_length=500)
    environment_image_url: Optional[str] = Field(default=None, max_length=500)

    doctor_spotlight_name: Optional[str] = Field(default=None, max_length=200)
    doctor_spotlight_kind: Optional[Literal["owner", "lead_doctor"]] = None
    doctor_spotlight_role: Optional[str] = Field(default=None, max_length=200)
    doctor_spotlight_specialties: Optional[List[str]] = Field(default=None, max_length=8)
    doctor_spotlight_bio: Optional[str] = Field(default=None, max_length=1000)
    team_note: Optional[str] = Field(default=None, max_length=500)

    clinic_story: Optional[str] = Field(default=None, max_length=1500)
    environment_description: Optional[str] = Field(default=None, max_length=1000)
    consultation_process: Optional[str] = Field(default=None, max_length=1000)

    review_sources: Optional[ClinicReviewSources] = None
    case_library: Optional[List[ClinicProfileCase]] = None

    # ── Phase C1 — Premium / Authority enrichment fields ───────────
    # Additive; missing on existing clinics → rendered as polished
    # empty states ("Тази секция е включена в профила, но клиниката
    # все още не е добавила съдържание."). NEVER seeded with mock
    # data on real clinics.
    technology_section: Optional[List[str]] = None  # Authority: bullets
    expert_qa: Optional[List[ClinicProfileQA]] = None  # Authority
    philosophy: Optional[str] = Field(default=None, max_length=800)  # Premium+
    faq: Optional[List[ClinicProfileQA]] = None  # Premium+
    category_authority: Optional[str] = Field(default=None, max_length=300)  # Authority
    price_ranges: Optional[List[ClinicProfilePriceRange]] = None  # Authority
    # Per-treatment expansion. Key is the treatment slug
    # (e.g. "invisalign", "implants").
    treatment_details: Optional[Dict[str, ClinicProfileTreatmentDetail]] = None

    updated_at: Optional[str] = None
    published_at: Optional[str] = None


class ClinicAdminUpdate(BaseModel):
    """Admin can patch any of these. All optional."""
    model_config = ConfigDict(extra="ignore")
    clinic_name: Optional[str] = Field(default=None, max_length=200)
    city: Optional[str] = Field(default=None, max_length=100)
    address: Optional[str] = Field(default=None, max_length=500)
    phone: Optional[str] = Field(default=None, max_length=50)
    email: Optional[EmailStr] = None
    website: Optional[str] = Field(default=None, max_length=500)
    contact_person: Optional[str] = Field(default=None, max_length=200)
    treatments_offered: Optional[List[str]] = None
    # Canonical going forward (Feb 2026 cleanup). Admin frontend may send
    # either key; the router writes both to keep legacy readers working.
    treatments_supported: Optional[List[str]] = None
    clinic_status: Optional[str] = None
    subscription_status: Optional[str] = None
    monthly_plan: Optional[str] = Field(default=None, max_length=100)
    notification_email: Optional[EmailStr] = None
    description: Optional[str] = Field(default=None, max_length=2000)

    # ── Rich Profile Editor R1 ───────────────────────────────────────
    partner_tier: Optional[str] = None
    clinic_profile: Optional[ClinicProfile] = None

    # ── Feb 2026 pricing revamp — accepted on PATCH ────────────
    base_package: Optional[str] = None
    founding_status: Optional[str] = None
    billing_status: Optional[str] = None
    billing_cadence: Optional[str] = None
    monthly_price_eur: Optional[float] = None
    annual_price_eur: Optional[float] = None
    onboarding_fee_eur: Optional[float] = None
    founding_start_date: Optional[str] = None
    founding_end_date: Optional[str] = None
    private_terms_notes: Optional[str] = Field(default=None, max_length=2000)
    strategic_public_display: Optional[bool] = None
    # `entitlement_overrides` — list of {key, value, note} rows. Router
    # normalises + attaches `at`/`by` on write.
    entitlement_overrides: Optional[List[Dict[str, Any]]] = None

    # ── Phase C1 — sponsorship & showcase flags ──────────────────────
    # `is_sponsored` toggles a visually-separated "Спонсорирано" badge
    # on the profile/listing. Per product rule it MUST NOT change
    # ranking. `sponsored_label` is reserved for future per-campaign
    # variations; for now the public render forces the literal string
    # "Спонсорирано" regardless of stored value.
    # `is_addons_showcase` flags the dedicated demo clinic that renders
    # every paid visual add-on; combined with `is_demo=True` it stays
    # excluded from listings / recommendations / sitemap.
    is_sponsored: Optional[bool] = None
    sponsored_label: Optional[str] = Field(default=None, max_length=80)
    is_addons_showcase: Optional[bool] = None

    # ── External review signals (display-only, admin-gated) ──────────
    # All fields are optional. Bounds match the publish gate in
    # `backend/routers/public.py::_build_review_signals`. The router is the
    # ultimate authority on whether a value is surfaced publicly; the
    # schema here only validates write-side admin input.
    google_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    google_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    google_place_url: Optional[str] = Field(default=None, max_length=500)
    facebook_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    facebook_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    facebook_page_url: Optional[str] = Field(default=None, max_length=500)
    superdoc_rating: Optional[float] = Field(default=None, ge=0.0, le=5.0)
    superdoc_review_count: Optional[int] = Field(default=None, ge=0, le=100_000)
    superdoc_profile_url: Optional[str] = Field(default=None, max_length=500)
    review_sources_last_checked_at: Optional[datetime] = None
    review_sources_verified_by_admin: Optional[bool] = None

    # ── Aligner brand / provider tags (Feb 2026) ─────────────────
    # Structured list of brand entries; validated and normalised in
    # the router layer via `aligner_brands.normalize_aligner_brand_entries`.
    # We accept `Any` here so the strict whitelist enforcement stays in
    # one place (the helper) and produces a uniform 400 response.
    aligner_brands_supported: Optional[List[Dict[str, Any]]] = None


class ConsultationRequestCreate(BaseModel):
    """Admin creates a consultation request directly (rare — usually
    auto-created from a lead assign). Allows manual entry too."""
    model_config = ConfigDict(extra="ignore")
    patient_name: str = Field(min_length=1, max_length=200)
    patient_phone: str = Field(min_length=1, max_length=50)
    patient_email: Optional[EmailStr] = None
    patient_city: Optional[str] = Field(default=None, max_length=100)
    treatment_interest: str = Field(min_length=1, max_length=100)
    preferred_contact_time: Optional[str] = Field(default=None, max_length=200)
    urgency: Optional[str] = Field(default=None, max_length=50)
    readiness: Optional[str] = Field(default=None, max_length=50)
    quiz_result_id: Optional[str] = None
    lead_id: Optional[str] = None
    source: Optional[str] = Field(default=None, max_length=100)
    utm_source: Optional[str] = Field(default=None, max_length=300)
    utm_campaign: Optional[str] = Field(default=None, max_length=300)
    utm_adset: Optional[str] = Field(default=None, max_length=300)
    utm_ad: Optional[str] = Field(default=None, max_length=300)
    assigned_clinic_id: Optional[str] = None


class ConsultationAssignClinic(BaseModel):
    clinic_id: str = Field(min_length=1, max_length=100)


class ConsultationAdminPatch(BaseModel):
    model_config = ConfigDict(extra="ignore")
    status: Optional[str] = None
    notes: Optional[str] = Field(default=None, max_length=5000)


class AppointmentDetails(BaseModel):
    """Embedded payload when clinic books or reschedules a consultation."""
    appointment_type: str
    start_time: str  # ISO 8601
    end_time: str  # ISO 8601
    notes: Optional[str] = Field(default=None, max_length=2000)


class ConsultationActionRequest(BaseModel):
    """Body for /api/clinic/consultation-requests/{id}/action."""
    action_type: str
    note: Optional[str] = Field(default=None, max_length=2000)
    appointment: Optional[AppointmentDetails] = None


class ClinicAppointmentCreate(BaseModel):
    """Direct calendar entry (clinic creates an appointment without a request).
    Rare — usually appointments are created via the action endpoint."""
    model_config = ConfigDict(extra="ignore")
    consultation_request_id: Optional[str] = None
    patient_name: str = Field(min_length=1, max_length=200)
    patient_phone: str = Field(min_length=1, max_length=50)
    treatment_category: Optional[str] = Field(default=None, max_length=100)
    appointment_type: str
    start_time: str
    end_time: str
    notes: Optional[str] = Field(default=None, max_length=2000)


class ClinicAppointmentPatch(BaseModel):
    model_config = ConfigDict(extra="ignore")
    appointment_type: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    status: Optional[str] = None
    notes: Optional[str] = Field(default=None, max_length=2000)


# ─── Phase D — Online Orientation Settings (June 2026) ───────────────
# Operational/admin foundation for Free Online Orientation. This is
# settings + availability ONLY — no booking requests, no slot locks,
# no patient-facing UI. Patient eligibility lives in Phase E.

ORIENTATION_DAY_OF_WEEK_VALUES = (
    "monday", "tuesday", "wednesday", "thursday",
    "friday", "saturday", "sunday",
)

# Treatment categories the patient could be routed to for an
# orientation. Kept tier-agnostic and treatment-category-only — no
# clinical brand/marketing terms. Admin can extend later by editing the
# constant; the frontend Picker reads `ORIENTATION_TREATMENT_CATEGORIES`.
ORIENTATION_TREATMENT_CATEGORIES = (
    "orthodontics",
    "aligners",
    "implants",
    "cosmetic_dentistry",
    "general_orientation",
)

# Access-status enum returned by `orientation_access.get_online_orientation_access_status`.
# Phase E will branch on these values to compute patient-facing
# eligibility on the result page.
ORIENTATION_ACCESS_STATUS_VALUES = (
    "included_in_plan",
    "addon_enabled",
    "disabled_by_admin",
    "not_available",
    "clinic_inactive",
)

# Sensible operational defaults — surfaced to the admin UI and used
# when no settings doc exists yet for a clinic.
ORIENTATION_DEFAULTS = {
    "monthly_free_slot_limit": 10,
    "slot_duration_minutes": 20,
    "max_bookings_per_day": 2,
    "booking_buffer_minutes": 15,
    "eligible_treatment_categories": [
        "orthodontics", "aligners", "implants",
        "cosmetic_dentistry", "general_orientation",
    ],
}


def _validate_hhmm(v: str) -> str:
    """Allow HH:MM (24h). Raises ValueError on malformed input.
    Used for availability rows."""
    if not isinstance(v, str):
        raise ValueError("time must be a string HH:MM")
    parts = v.strip().split(":")
    if len(parts) != 2:
        raise ValueError("time must be HH:MM")
    try:
        h, m = int(parts[0]), int(parts[1])
    except ValueError:
        raise ValueError("time must be HH:MM with integer parts")
    if not (0 <= h <= 23 and 0 <= m <= 59):
        raise ValueError("time must be 00:00–23:59")
    return f"{h:02d}:{m:02d}"


class ClinicOnlineOrientationAvailability(BaseModel):
    """A single weekly availability window for a clinic's online
    orientation. Used to draw the per-day timeline in admin UI; Phase E
    will turn these into actual slot candidates."""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    clinic_id: str
    day_of_week: str
    start_time: str
    end_time: str
    is_active: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("day_of_week")
    @classmethod
    def _v_dow(cls, v: str) -> str:
        v = v.strip().lower()
        if v not in ORIENTATION_DAY_OF_WEEK_VALUES:
            raise ValueError(f"day_of_week must be one of {ORIENTATION_DAY_OF_WEEK_VALUES}")
        return v

    @field_validator("start_time", "end_time")
    @classmethod
    def _v_time(cls, v: str) -> str:
        return _validate_hhmm(v)


class ClinicOnlineOrientationAvailabilityCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    day_of_week: str
    start_time: str
    end_time: str
    is_active: bool = True

    @field_validator("day_of_week")
    @classmethod
    def _v_dow(cls, v: str) -> str:
        v = v.strip().lower()
        if v not in ORIENTATION_DAY_OF_WEEK_VALUES:
            raise ValueError(f"day_of_week must be one of {ORIENTATION_DAY_OF_WEEK_VALUES}")
        return v

    @field_validator("start_time", "end_time")
    @classmethod
    def _v_time(cls, v: str) -> str:
        return _validate_hhmm(v)


class ClinicOnlineOrientationAvailabilityUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    day_of_week: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    is_active: Optional[bool] = None

    @field_validator("day_of_week")
    @classmethod
    def _v_dow(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        v = v.strip().lower()
        if v not in ORIENTATION_DAY_OF_WEEK_VALUES:
            raise ValueError(f"day_of_week must be one of {ORIENTATION_DAY_OF_WEEK_VALUES}")
        return v

    @field_validator("start_time", "end_time")
    @classmethod
    def _v_time(cls, v: Optional[str]) -> Optional[str]:
        return _validate_hhmm(v) if v is not None else None


class ClinicOnlineOrientationSettings(BaseModel):
    """Per-clinic Online Orientation configuration. Stored in
    `clinic_online_orientation_settings`, keyed by `clinic_id` (one
    doc per clinic). All flags default to operationally-OFF — even
    Premium plans require explicit admin enablement before patient
    funnels can route to this clinic."""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    clinic_id: str

    # Operational on/off (admin toggle). Even Premium clinics need this
    # to be true before the patient funnel routes to them.
    enabled: bool = False

    # Basic tier add-on. Only meaningful for `standard` / `featured`
    # tiers; ignored for Premium (Premium is always included-in-plan).
    addon_enabled_for_basic: bool = False

    # Funnel rules.
    requires_quiz_completion: bool = True
    requires_contact_details: bool = True

    monthly_free_slot_limit: int = Field(default=10, ge=0, le=1000)
    slot_duration_minutes: int = Field(default=20, ge=5, le=240)
    max_bookings_per_day: int = Field(default=2, ge=0, le=100)
    booking_buffer_minutes: int = Field(default=15, ge=0, le=240)

    eligible_treatment_categories: List[str] = Field(
        default_factory=lambda: list(ORIENTATION_DEFAULTS["eligible_treatment_categories"])
    )

    public_description: Optional[str] = Field(default=None, max_length=600)
    disclaimer_text: Optional[str] = Field(default=None, max_length=600)
    internal_admin_notes: Optional[str] = Field(default=None, max_length=1500)

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("eligible_treatment_categories")
    @classmethod
    def _v_cats(cls, v: List[str]) -> List[str]:
        if not isinstance(v, list):
            raise ValueError("eligible_treatment_categories must be a list")
        out: List[str] = []
        for c in v:
            if not isinstance(c, str):
                raise ValueError("category must be a string")
            cs = c.strip().lower()
            if cs not in ORIENTATION_TREATMENT_CATEGORIES:
                raise ValueError(
                    f"category '{c}' is not allowed; pick from {ORIENTATION_TREATMENT_CATEGORIES}"
                )
            if cs not in out:
                out.append(cs)
        return out


class ClinicOnlineOrientationSettingsUpdate(BaseModel):
    """Admin PATCH payload. All optional so partial updates work."""
    model_config = ConfigDict(extra="ignore")
    enabled: Optional[bool] = None
    addon_enabled_for_basic: Optional[bool] = None
    requires_quiz_completion: Optional[bool] = None
    requires_contact_details: Optional[bool] = None
    monthly_free_slot_limit: Optional[int] = Field(default=None, ge=0, le=1000)
    slot_duration_minutes: Optional[int] = Field(default=None, ge=5, le=240)
    max_bookings_per_day: Optional[int] = Field(default=None, ge=0, le=100)
    booking_buffer_minutes: Optional[int] = Field(default=None, ge=0, le=240)
    eligible_treatment_categories: Optional[List[str]] = None
    public_description: Optional[str] = Field(default=None, max_length=600)
    disclaimer_text: Optional[str] = Field(default=None, max_length=600)
    internal_admin_notes: Optional[str] = Field(default=None, max_length=1500)

    @field_validator("eligible_treatment_categories")
    @classmethod
    def _v_cats(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        if v is None:
            return v
        return ClinicOnlineOrientationSettings._v_cats(v)  # type: ignore[attr-defined]


# ─── Phase E — Online Orientation Bookings (June 2026) ────────────
# Patient submits a request to a specific clinic + slot. Booking starts
# as `pending_clinic_confirmation` and a soft lock is held on the slot
# for 24h. Clinic confirms / rejects / cancels via the clinic dashboard.
# NO Care Pass unlock here — that is Phase F.

ORIENTATION_BOOKING_STATUS_VALUES = (
    "pending_clinic_confirmation",
    "confirmed_by_clinic",
    "rejected_by_clinic",
    "expired_pending_confirmation",
    "scheduled",
    "completed",
    "no_show",
    "cancelled_by_patient",
    "cancelled_by_clinic",
    "converted_to_in_clinic",
    "not_suitable",
    "needs_admin_review",
)

# Statuses that hold an active lock on the slot — these block another
# patient from picking the same slot.
ORIENTATION_BOOKING_ACTIVE_LOCK_STATUSES = (
    "pending_clinic_confirmation",
    "confirmed_by_clinic",
    "scheduled",
)

ORIENTATION_TOPIC_VALUES = (
    "aligners_braces",
    "implants",
    "cosmetic",
    "gums_periodontology",
    "not_sure",
    "other",
)

ORIENTATION_TOPIC_LABELS_BG = {
    "aligners_braces": "Алайнери / брекети",
    "implants": "Импланти",
    "cosmetic": "Естетична стоматология",
    "gums_periodontology": "Венци / пародонтология",
    "not_sure": "Не съм сигурен откъде да започна",
    "other": "Друго",
}

# Clinic / admin booking-action types.
ORIENTATION_BOOKING_ACTION_VALUES = (
    "confirm",
    "reject",
    "cancel",
    "mark_completed",
    "mark_no_show",
    "mark_converted_to_in_clinic",
    "mark_not_suitable",
    "add_note",
)


class OnlineOrientationBookingCreate(BaseModel):
    """Patient-side payload. Does NOT take name/phone/email — those are
    read server-side from the unlocked lead doc."""
    model_config = ConfigDict(extra="ignore")
    clinic_id: str = Field(min_length=1, max_length=100)
    scheduled_at: str = Field(min_length=10, max_length=40)  # ISO 8601 UTC
    topic: str
    treatment_category: Optional[str] = Field(default=None, max_length=80)
    consent_confirmed: bool = False
    disclaimer_acknowledged: bool = False
    patient_note: Optional[str] = Field(default=None, max_length=500)

    @field_validator("topic")
    @classmethod
    def _v_topic(cls, v: str) -> str:
        if v not in ORIENTATION_TOPIC_VALUES:
            raise ValueError(f"topic must be one of {ORIENTATION_TOPIC_VALUES}")
        return v


class OnlineOrientationBookingClinicAction(BaseModel):
    """Clinic dashboard action body."""
    model_config = ConfigDict(extra="ignore")
    action: str
    note: Optional[str] = Field(default=None, max_length=2000)

    @field_validator("action")
    @classmethod
    def _v_action(cls, v: str) -> str:
        if v not in ORIENTATION_BOOKING_ACTION_VALUES:
            raise ValueError(f"action must be one of {ORIENTATION_BOOKING_ACTION_VALUES}")
        return v


class OnlineOrientationBookingAdminAction(BaseModel):
    """Admin override action body — same shape as clinic action, plus
    an admin-only `release_slot` flag for manual unlock of stuck slots."""
    model_config = ConfigDict(extra="ignore")
    action: str
    note: Optional[str] = Field(default=None, max_length=2000)
    release_slot: bool = False

    @field_validator("action")
    @classmethod
    def _v_action(cls, v: str) -> str:
        if v not in ORIENTATION_BOOKING_ACTION_VALUES:
            raise ValueError(f"action must be one of {ORIENTATION_BOOKING_ACTION_VALUES}")
        return v



# ─── Public Clinic Profile Scheduler (Phase A — clinic homepage) ─────
# A patient on /clinics/<slug> (or any public clinic profile) can book a
# phone consultation directly without going through the quiz funnel.
# We auto-create a minimal lead with strict labels so admin / clinic
# can distinguish this source from quiz-qualified leads, then reuse the
# existing `online_orientation_bookings` collection + state machine.
PUBLIC_CONSULTATION_TYPE_VALUES = ("phone_consultation",)


class PublicConsultationBookingCreate(BaseModel):
    """Public payload from clinic profile scheduler. Carries the patient
    contact directly (no `lead_id` because no quiz happened). Server
    creates a minimal lead and links the booking back."""
    model_config = ConfigDict(extra="ignore")
    clinic_id: str = Field(min_length=1, max_length=100)
    scheduled_at: str = Field(min_length=10, max_length=40)  # ISO 8601 UTC
    consultation_type: str = Field(default="phone_consultation", max_length=40)
    name: str = Field(min_length=1, max_length=200)
    phone: str = Field(min_length=4, max_length=50)
    email: EmailStr
    patient_note: Optional[str] = Field(default=None, max_length=500)
    consent: bool = False
    disclaimer_acknowledged: bool = False
    source_path: Optional[str] = Field(default=None, max_length=500)
    utm_source: Optional[str] = Field(default=None, max_length=300)
    utm_campaign: Optional[str] = Field(default=None, max_length=300)

    @field_validator("consultation_type")
    @classmethod
    def _v_type(cls, v: str) -> str:
        if v not in PUBLIC_CONSULTATION_TYPE_VALUES:
            raise ValueError(
                f"consultation_type must be one of {PUBLIC_CONSULTATION_TYPE_VALUES}"
            )
        return v

    @field_validator("name", "phone", mode="before")
    @classmethod
    def _strip_required(cls, v):
        if isinstance(v, str):
            return v.strip()
        return v



# ═══════════════════════════════════════════════════════════════════
#  Clinic add-ons (Feb 2026 pricing revamp)
# ═══════════════════════════════════════════════════════════════════
# Stored in `clinic_addons` collection. Read-side helpers live in
# `backend/addon_catalog.py`. Router: `backend/routers/clinic_addons.py`.

class ClinicAddonCreate(BaseModel):
    """Body for `POST /api/admin/clinics/{clinic_id}/addons`. When
    `add_on_id` matches a catalog entry, the router auto-fills `name`
    and `price_eur` from the catalog on save (admin can override)."""
    model_config = ConfigDict(extra="ignore")

    add_on_id: str = Field(min_length=1, max_length=80)
    category: str = Field(min_length=1, max_length=40)
    name: str = Field(min_length=1, max_length=200)
    price_eur: Optional[float] = None
    billing_type: str = "one_time"
    status: str = "proposed"
    start_date: Optional[str] = None  # ISO date
    end_date: Optional[str] = None    # ISO date
    public_visibility: str = "internal_only"
    # Guardrail — hard-coded FALSE at the router level regardless of
    # what is submitted here.
    affects_organic_matching: bool = False
    internal_owner: Optional[str] = Field(default=None, max_length=120)
    delivery_notes: Optional[str] = Field(default=None, max_length=2000)
    invoice_notes: Optional[str] = Field(default=None, max_length=2000)


class ClinicAddonUpdate(BaseModel):
    """Partial PATCH body — every field optional."""
    model_config = ConfigDict(extra="ignore")

    category: Optional[str] = Field(default=None, max_length=40)
    name: Optional[str] = Field(default=None, max_length=200)
    price_eur: Optional[float] = None
    billing_type: Optional[str] = None
    status: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    public_visibility: Optional[str] = None
    internal_owner: Optional[str] = Field(default=None, max_length=120)
    delivery_notes: Optional[str] = Field(default=None, max_length=2000)
    invoice_notes: Optional[str] = Field(default=None, max_length=2000)


# ─── Patient accounts (Общност — Phase 1, OTP-only) ───────────────

class PatientOtpRequest(BaseModel):
    """Step 1 of passwordless login: ask for a one-time code by email."""
    email: EmailStr


class PatientOtpVerify(BaseModel):
    """Step 2: exchange the emailed 6-digit code for a session."""
    email: EmailStr
    code: str = Field(min_length=6, max_length=6, pattern=r"^\d{6}$")
    # Optional: link this specific lead to the account being logged into,
    # even if the lead has no email yet (e.g. a patient on /results/[leadId]
    # who hasn't reached contact-capture). See patient_verify_otp.
    claim_lead_id: Optional[str] = Field(default=None, max_length=64)


class PatientProfileUpdate(BaseModel):
    """Patient self-service profile edit. All fields optional/partial."""
    display_name: Optional[str] = Field(default=None, min_length=2, max_length=60)
    city_slug: Optional[str] = Field(default=None, max_length=60)


class PatientOut(BaseModel):
    """Public-safe patient projection returned to the patient themselves."""
    id: str
    email: EmailStr
    email_verified: bool = True
    display_name: Optional[str] = None
    city_slug: Optional[str] = None
    reputation: int = 0
    created_at: Optional[str] = None


class PatientTokenResponse(BaseModel):
    # access_token omitted in cookie-only mode (response_model_exclude_none).
    access_token: Optional[str] = None
    token_type: Optional[str] = None
    user: PatientOut
    # Only set when the request carried claim_lead_id. One of:
    # "claimed" | "already_mine" | "already_claimed_by_other" | "lead_not_found"
    claim_result: Optional[str] = None


# ─── Общност (Q&A) — Phase 2 (questions + browse + moderation) ─────

class QaQuestionCreate(BaseModel):
    """A patient asking a question. Body is sanitized + PII-scrubbed server-side."""
    topic: str = Field(min_length=2, max_length=40)
    title: str = Field(min_length=10, max_length=160)
    body: str = Field(min_length=20, max_length=4000)


class QaReportCreate(BaseModel):
    """Flag a question (or later, an answer) for moderator attention."""
    reason: str = Field(min_length=3, max_length=500)


class QaModerationBody(BaseModel):
    moderation_notes: Optional[str] = Field(default=None, max_length=2000)


class QaAnswerCreate(BaseModel):
    """An answer from either a patient (peer) or a clinic (expert)."""
    body: str = Field(min_length=10, max_length=3000)


# ─── Multi-doctor booking system (Phase 1 — doctor roster) ─────────
# A clinic-owned roster of doctors. Specialties reuse the same
# treatment-category vocabulary as online orientation eligibility
# (`ORIENTATION_TREATMENT_CATEGORIES`) so a request's treatment_category
# can be matched against a doctor's specialties in assignment UI.
# Deliberately deactivate-only (never hard-deleted) so historical
# bookings keep a valid doctor reference.

def _validate_doctor_specialties(v: List[str]) -> List[str]:
    if not isinstance(v, list):
        raise ValueError("specialties must be a list")
    out: List[str] = []
    for s in v:
        if not isinstance(s, str):
            raise ValueError("specialty must be a string")
        ss = s.strip().lower()
        if ss not in ORIENTATION_TREATMENT_CATEGORIES:
            raise ValueError(
                f"specialty '{s}' is not allowed; pick from {ORIENTATION_TREATMENT_CATEGORIES}"
            )
        if ss not in out:
            out.append(ss)
    return out


class Doctor(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    clinic_id: str
    name: str = Field(min_length=1, max_length=200)
    title: Optional[str] = Field(default=None, max_length=200)
    specialties: List[str] = Field(default_factory=list)
    accepts_online: bool = True
    accepts_in_person: bool = True
    active: bool = True
    photo_url: Optional[str] = None
    bio: Optional[str] = Field(default=None, max_length=2000)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("specialties")
    @classmethod
    def _v_specialties(cls, v: List[str]) -> List[str]:
        return _validate_doctor_specialties(v)


class DoctorCreate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str = Field(min_length=1, max_length=200)
    title: Optional[str] = Field(default=None, max_length=200)
    specialties: List[str] = Field(default_factory=list)
    accepts_online: bool = True
    accepts_in_person: bool = True
    photo_url: Optional[str] = None
    bio: Optional[str] = Field(default=None, max_length=2000)

    @field_validator("specialties")
    @classmethod
    def _v_specialties(cls, v: List[str]) -> List[str]:
        return _validate_doctor_specialties(v)


class DoctorUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: Optional[str] = Field(default=None, min_length=1, max_length=200)
    title: Optional[str] = Field(default=None, max_length=200)
    specialties: Optional[List[str]] = None
    accepts_online: Optional[bool] = None
    accepts_in_person: Optional[bool] = None
    active: Optional[bool] = None
    photo_url: Optional[str] = None
    bio: Optional[str] = Field(default=None, max_length=2000)

    @field_validator("specialties")
    @classmethod
    def _v_specialties(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        if v is None:
            return v
        return _validate_doctor_specialties(v)


class DoctorAssignmentBody(BaseModel):
    """Staff-internal doctor assignment on an already-existing booking
    (physical appointment or online orientation booking). Availability
    stays clinic-wide — this never affects slot generation, it only
    labels which doctor is handling a booking that already exists.
    `doctor_id=None` clears the assignment."""
    model_config = ConfigDict(extra="ignore")
    doctor_id: Optional[str] = None
